name: tests

on: [push, pull_request]

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install mpmath
    - name: Install mpsci
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest

  test-macos-13:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install mpmath
    - name: Install mpsci
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest

  test-mpmath-alpha:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependences
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel pytest
        python -m pip install mpmath==1.4.0a5
    - name: Install mpsci
      run: |
        python -m pip install --no-build-isolation .
    - name: Test with pytest
      run: |
        python -m pytest
